version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal

after_build:
- 7z a Game.zip Spike_Project\Debug\Spike_FlanStudio.exe
- 7z a Game.zip Spike_Project\Resources
- 7z a Game.zip Spike_Project\*.dll

artifacts:
  - path: Game.zip
  #- name: ReleaseBaby
