version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
  
# bin\$(configuration)\*.dll
# bin\Spike Project\Debug\Spike_FlanStudio.exe

artifacts:
  - path: bin
  - name: ReleaseBaby
