version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal

after_build:
  - cmd: 7z a myapp.zip %APPVEYOR_BUILD_FOLDER%\path\Debug
  
artifacts:
  - path: myapp.zip
  - name: MyApp
