version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal

after_build:
- 7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\Spike Project\Debug\Spike_FlanStudio.exe"
- 7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\Spike Project\Resources"
- 7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\Spike Project\*.dll"
- 7z a SpikeFromAppveyor.zip "%APPBEYOR_BUILD_FOLDER%\README.md"

artifacts:
  - path: SpikeFromAppveyor.zip
    name: ReleaseBaby
